# Generated by Django 5.2.1 on 2025-05-21 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medicos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enfermeiros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do Enfermeiro', max_length=200, verbose_name='Nome')),
                ('coren', models.CharField(help_text='COREN do enfermeiro', max_length=6, verbose_name='COREN')),
                ('atuacao', models.CharField(help_text='Setor de Atuação do Enfermeiro', max_length=200, verbose_name='Setor de Atuação')),
                ('telefone', models.CharField(help_text='Telefone de Contato', max_length=9, verbose_name='Telefone')),
                ('email', models.CharField(help_text='Email do RG', max_length=200, verbose_name='Email')),
                ('data_nacimento', models.DateField(help_text='Data de Nacimento', verbose_name='Data de Nacimento')),
                ('cpf', models.CharField(help_text='CPF do Medico', max_length=12, verbose_name='CPF')),
                ('status', models.CharField(choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo')], help_text='Status do medico', max_length=100, verbose_name='Status')),
            ],
            options={
                'verbose_name': ('Enfermeiro',),
                'verbose_name_plural': 'Enfermeiros',
            },
        ),
        migrations.AlterField(
            model_name='medico',
            name='status',
            field=models.CharField(choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo')], max_length=100),
        ),
    ]
