# Generated by Django 5.2.1 on 2025-05-21 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medicos', '0003_pacientes_alter_enfermeiros_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacientes',
            name='data_nacimento',
            field=models.DateField(help_text='Data de Nacimento', null=True, verbose_name='Data de Nacimento'),
        ),
        migrations.AddField(
            model_name='pacientes',
            name='nome',
            field=models.CharField(help_text='Nome do Paciente', max_length=200, null=True, verbose_name='Nome'),
        ),
    ]
