# Generated by Django 5.2.1 on 2025-05-21 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medicos', '0004_pacientes_data_nacimento_pacientes_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enfermeiros',
            name='atuacao',
            field=models.CharField(choices=[('Pediatra', 'Pediatra'), ('Oftamologista', 'Oftamologista')], help_text='Setor de Atuação do Enfermeiro', max_length=200, null=True, verbose_name='Setor de Atuação'),
        ),
    ]
