# Generated by Django 5.2.1 on 2025-05-21 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medicos', '0005_alter_enfermeiros_atuacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='cpf',
            field=models.IntegerField(help_text='CPF do Medico', verbose_name='CPF'),
        ),
    ]
