# Generated by Django 5.2.1 on 2025-05-22 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medicos', '0006_alter_medico_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='cpf',
            field=models.CharField(help_text='CPF do Medico', max_length=12, verbose_name='CPF'),
        ),
    ]
