# Generated by Django 5.2.1 on 2025-05-25 16:47

import Medicos.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medicos', '0008_especialidade_alter_pacientes_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='cpf',
            field=models.CharField(help_text='CPF do Medico', max_length=12, unique=True, validators=[Medicos.validators.validate_cpf], verbose_name='CPF'),
        ),
    ]
